import os
import requests
import json
from typing import Any, List, Mapping, Optional, Dict, Union

from langchain_core.callbacks.manager import CallbackManagerForLLMRun
from langchain_core.language_models.llms import BaseLLM
from langchain_core.outputs import Generation, LLMResult

# Try to load .env variables if python-dotenv is available
try:
    from dotenv import load_dotenv
    load_dotenv()
except ImportError:
    # python-dotenv not found, proceed without it
    pass

SUPABASE_FUNC_URL_ENV_VAR = "SUPABASE_SWIFT_ENDPOINT_URL"
SUPABASE_ANON_KEY_ENV_VAR = "SUPABASE_ANON_KEY"
SUPABASE_SERVICE_ROLE_KEY_ENV_VAR = "SUPABASE_SERVICE_ROLE_KEY"
DEFAULT_SUPABASE_FUNC_URL = "https://oykjekipibwtzujqpgec.supabase.co/functions/v1/swift-endpoint"

class SupabaseOpenAI(BaseLLM):
    """Custom Langchain LLM wrapper for a Supabase Edge Function proxying OpenAI."""

    supabase_function_url: str
    supabase_anon_key: Optional[str] = None
    supabase_service_role_key: Optional[str] = None
    timeout: int = 60  # seconds for HTTP request timeout

    def __init__(
        self,
        supabase_function_url: Optional[str] = None,
        timeout: int = 60,
        **kwargs: Any,
    ) -> None:
        # Resolve the actual URL that will be used for the Pydantic field
        resolved_supabase_url = supabase_function_url or os.getenv(SUPABASE_FUNC_URL_ENV_VAR, DEFAULT_SUPABASE_FUNC_URL)
        
        if not resolved_supabase_url:
            # This error will be raised if the URL cannot be determined, 
            # preventing Pydantic's missing field error with a more specific message.
            raise ValueError(
                f"Supabase function URL must be provided either as an argument, via the "
                f"{SUPABASE_FUNC_URL_ENV_VAR} environment variable, or have a default value. Currently unresolved."
            )

        # Prepare the arguments for Pydantic model initialization (super().__init__)
        # This must include all fields defined in SupabaseOpenAI that we want to set,
        # and any kwargs intended for the parent BaseLLM.
        init_data = kwargs.copy()  # Start with kwargs passed for BaseLLM or other fields
        init_data['supabase_function_url'] = resolved_supabase_url
        init_data['timeout'] = timeout
        # Load Supabase auth keys from env vars, they are optional at init, but _call will check
        init_data['supabase_anon_key'] = os.getenv(SUPABASE_ANON_KEY_ENV_VAR)
        init_data['supabase_service_role_key'] = os.getenv(SUPABASE_SERVICE_ROLE_KEY_ENV_VAR)
        
        super().__init__(**init_data)
        # Pydantic has initialized the fields: self.supabase_function_url, self.timeout, 
        # self.supabase_anon_key, self.supabase_service_role_key

    @property
    def _llm_type(self) -> str:
        return "supabase_openai_proxy"

    def _call(
        self,
        prompt: str,
        stop: Optional[List[str]] = None,
        run_manager: Optional[CallbackManagerForLLMRun] = None,
        **kwargs: Any,
    ) -> str:
        """Call out to the Supabase Edge Function.

        Args:
            prompt: The prompt to pass into the model.
            stop: Optional list of stop words to pass to the model.
                  Note: The Supabase function provided does not seem to support 'stop' directly.
                        This will be ignored by the endpoint but is part of BaseLLM signature.
            run_manager: Optional callback manager.
            **kwargs: Additional keyword arguments to pass to the model.
                      Supported by the Supabase function: messages, maxTokens, temperature, force_json.

        Returns:
            The string generated by the model.
        """
        headers = {
            "Content-Type": "application/json",
        }
        if self.supabase_anon_key:
            headers["apikey"] = self.supabase_anon_key
        if self.supabase_service_role_key:
            headers["Authorization"] = f"Bearer {self.supabase_service_role_key}"
        
        if not self.supabase_anon_key and not self.supabase_service_role_key:
            # Warn if no Supabase auth keys are found, as this is likely to cause 401
            print(
                f"Warning: Neither {SUPABASE_ANON_KEY_ENV_VAR} nor {SUPABASE_SERVICE_ROLE_KEY_ENV_VAR} "
                f"are set. Calls to Supabase Edge Function may fail with 401 Unauthorized."
            )

        payload: Dict[str, Any] = {
            "prompt": prompt,
            "maxTokens": kwargs.get("max_tokens", kwargs.get("maxTokens", 512)), # Allow both camelCase and snake_case
            "temperature": kwargs.get("temperature", 0.7),
            "force_json": kwargs.get("force_json", False),
        }

        # If 'messages' are provided in kwargs, use them instead of 'prompt'
        if "messages" in kwargs and isinstance(kwargs["messages"], list):
            payload.pop("prompt", None) # Remove prompt if messages are present
            payload["messages"] = kwargs["messages"]
        
        # Remove None values from payload to avoid sending them
        payload = {k: v for k, v in payload.items() if v is not None}

        try:
            response = requests.post(
                self.supabase_function_url,
                headers=headers,
                json=payload,
                timeout=self.timeout,
            )
            response.raise_for_status()  # Raise an exception for bad status codes (4xx or 5xx)
        except requests.exceptions.RequestException as e:
            raise ValueError(f"Error calling Supabase Edge Function: {e}") from e

        try:
            result_json = response.json()
        except json.JSONDecodeError as e:
            raise ValueError(
                f"Error decoding JSON response from Supabase Edge Function: {e}\n"
                f"Response text: {response.text[:500]}..."
            ) from e

        if "error" in result_json:
            error_message = result_json.get("error", "Unknown error from Supabase function")
            status = result_json.get("status", "error")
            raise ValueError(f"Supabase function returned an error (status: {status}): {error_message}")

        if "text" not in result_json:
            raise ValueError("Invalid response from Supabase Edge Function: 'text' field missing.")

        return result_json["text"]

    def _generate(
        self,
        prompts: List[str],
        stop: Optional[List[str]] = None,
        run_manager: Optional[CallbackManagerForLLMRun] = None,
        **kwargs: Any,
    ) -> LLMResult:
        """Run the LLM on multiple prompts.

        Args:
            prompts: The prompts to pass into the model.
            stop: Optional list of stop words to pass to the model.
            run_manager: Optional callback manager.
            **kwargs: Additional keyword arguments to pass to the model.

        Returns:
            An LLMResult which contains a list of Generations.
        """
        generations = []
        for prompt in prompts:
            # Assuming _call handles kwargs appropriately for messages etc.
            # If _call is strictly for a single string prompt, and messages are handled
            # differently, this might need adjustment or _call needs to be more flexible.
            text = self._call(prompt, stop=stop, run_manager=run_manager, **kwargs)
            generations.append([Generation(text=text)])
        
        # If there's any token usage or other info returned by your Supabase function
        # that you want to capture, you'd parse it and include it in llm_output.
        # For now, it's minimal.
        llm_output: Optional[Mapping[str, Any]] = None 
        return LLMResult(generations=generations, llm_output=llm_output)

    # Optional: Implement _agenerate for async if needed
    # async def _agenerate(...)

    @property
    def _identifying_params(self) -> Mapping[str, Any]:
        """Get the identifying parameters."""
        return {
            "supabase_function_url": self.supabase_function_url,
            "timeout": self.timeout,
            # Not including keys in identifying_params for security/verbosity reasons
        }

if __name__ == '__main__':
    # Example Usage (requires .env file with SUPABASE_SWIFT_ENDPOINT_URL or OPENAI_API_KEY set in Supabase project)
    print("Testing SupabaseOpenAI LLM Wrapper...")
    
    # Ensure SUPABASE_SWIFT_ENDPOINT_URL is in your .env or pass it directly
    # For this test, it will use the default URL if not set in .env
    # Make sure your Supabase Edge Function has OPENAI_API_KEY set in its environment.
    
    custom_llm = SupabaseOpenAI()
    
    print(f"Using Supabase endpoint: {custom_llm.supabase_function_url}")

    try:
        # Test with prompt
        print("\n--- Test 1: Simple prompt ---")
        response_text = custom_llm.invoke("What is the capital of France?")
        print(f"Response: {response_text}")

        # Test with messages format
        print("\n--- Test 2: Messages format ---")
        messages = [
            {"role": "system", "content": "You are a helpful assistant."},
            {"role": "user", "content": "What are the first 3 prime numbers?"}
        ]
        response_text_messages = custom_llm.invoke("Placeholder prompt", messages=messages) # prompt is ignored if messages are present
        print(f"Response (messages): {response_text_messages}")

        # Test with force_json (ensure your prompt asks for JSON output)
        print("\n--- Test 3: Force JSON ---")
        json_prompt = "Return a JSON object with two keys: 'city' and 'country'. For Paris, France."
        response_text_json = custom_llm.invoke(json_prompt, force_json=True)
        print(f"Response (force_json): {response_text_json}")
        try:
            parsed_json = json.loads(response_text_json)
            print(f"Parsed JSON: {parsed_json}")
        except json.JSONDecodeError:
            print("Failed to parse JSON response from force_json test.")

    except ValueError as e:
        print(f"An error occurred during testing: {e}")
    except Exception as e:
        print(f"An unexpected error occurred: {e}")
