from pydantic import BaseModel, Field
from typing import Dict, Any, Optional, List
from datetime import datetime, timezone
import uuid

class SharableLearning(BaseModel):
    """Represents a piece of sharable knowledge or learning generated by an agent or crew."""
    learning_id: str = Field(default_factory=lambda: f"learn_{uuid.uuid4()}")
    source_entity_id: str # ID of the agent or crew that generated this learning
    learning_type: str = Field(description="Type of learning, e.g., 'prompt_template', 'heuristic_rule', 'config_parameters', 'model_weights_ref'")
    content: Dict[str, Any] = Field(description="The actual learning content, flexible based on learning_type.")
    # Example content structures:
    # For 'prompt_template': {"template": "...", "input_variables": [...], "notes": "..."}
    # For 'heuristic_rule': {"condition": "...", "action": "...", "confidence": 0.85}
    # For 'config_parameters': {"param_name": "value", ...}
    # For 'model_weights_ref': {"model_name": "...", "reference_uri": "s3://.../model.pt", "version": "1.2"}

    task_description: str = Field(description="Natural language description of the task or context to which this learning applies.")
    keywords: List[str] = Field(default_factory=list, description="Keywords for searchability and categorization.")
    
    performance_metric: Optional[str] = Field(default=None, description="Optional metric indicating the impact of this learning, e.g., 'accuracy_improvement:0.15'.")
    version: int = Field(default=1, description="Version of this learning item.")
    
    created_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
    updated_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))

    class Config:
        json_encoders = {
            datetime: lambda dt: dt.isoformat()
        }
        json_schema_extra = {
            "example": {
                "learning_id": "learn_123e4567-e89b-12d3-a456-426614174000",
                "source_entity_id": "agent_translation_optimizer_v2",
                "learning_type": "prompt_template",
                "content": {
                    "template": "Translate the following text to {target_language} with a {tone} tone: {text}",
                    "input_variables": ["target_language", "tone", "text"],
                    "notes": "Works well for informal texts."
                },
                "task_description": "Optimized prompt for informal text translation.",
                "keywords": ["translation", "prompt", "informal", "optimization"],
                "performance_metric": "bleu_score_increase:0.05",
                "version": 2,
                "created_at": "2023-10-26T10:00:00Z",
                "updated_at": "2023-10-27T11:30:00Z"
            }
        }

    def touch(self):
        """Updates the updated_at timestamp to the current time."""
        self.updated_at = datetime.now(timezone.utc)

    def to_redis_dict(self) -> Dict[str, Any]:
        """Converts the model to a dictionary suitable for Redis HSET, handling datetime.
           Pydantic's model_dump(mode='json') handles datetime to ISO string conversion.
        """
        return self.model_dump(mode='json')

    @classmethod
    def from_redis_dict(cls, data: Dict[str, Any]) -> 'SharableLearning':
        """Creates an instance from a dictionary retrieved from Redis.
           Pydantic will parse ISO strings back to datetime objects automatically.
        """
        return cls(**data)
